#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Roman
Version  : 1.24
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/C/CH/CHORNY/Roman-1.24.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CH/CHORNY/Roman-1.24.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libr/libroman-perl/libroman-perl_1.24-1.debian.tar.xz
Summary  : functions for converting between Roman and Arabic numerals
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Roman-license
Requires: perl-Roman-man

%description
Roman.pm version 1.23
NAME
Roman - Perl module for conversion between Roman and Arabic
numerals.

%package license
Summary: license components for the perl-Roman package.
Group: Default

%description license
license components for the perl-Roman package.


%package man
Summary: man components for the perl-Roman package.
Group: Default

%description man
man components for the perl-Roman package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Roman-1.24
mkdir -p %{_topdir}/BUILD/Roman-1.24/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Roman-1.24/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Roman
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Roman/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Roman.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Roman/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Roman.3
